apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: complete-devops-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/ramzihaj/Full-Automated-DevOps-Pipeline"
    targetRevision: HEAD
    path: "helm-chart/complete-devops-project"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  